name: Publish to PSGallery

on:
  push:
    branches: [ main ]
    paths:
      - 'mcrcon/**'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Publish to PSGallery
        shell: pwsh
        env:
          NUGET_API_KEY: ${{ secrets.NUGGETS }}
        run: |
          Publish-Module -Path ./mcrcon -NuGetApiKey $env:NUGET_API_KEY
